feat(products.controller) :
ITA-Dnipro/Dp-202-shop pull request #33
Opened 2021-05-23 15:02 UTC by ShumerPlema

add getOneProductById method;
add getAllProduct Method;
add getAllProductExtended Method;
add idIsExist method.
change error-handler.middleware

2021-05-23 18:00 UTC, kolesnicknick requested changes
return formation back. commit only lines you have changed

2021-05-23 18:00 UTC, kolesnicknick commented on .gitignore
> -./Dp-202-shop/node_modules/
return this back

2021-05-23 18:00 UTC, kolesnicknick commented on Dp-202-shop/server/src/modules/products/product.service.ts
> -import { NotFoundData } from '../../common/errors/notFoundData';
return proper formation back

2021-05-25 08:42 UTC, valeriia-danylenko approved these changes
Everything works and that's great

2021-05-25 09:42 UTC, DianaBondarenko approved these changes

2021-05-25 11:05 UTC, merged